# Generated by Django 3.2.5 on 2021-08-02 12:26

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210802_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetups',
            name='organizer_email',
            field=models.EmailField(default=2012, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
