# Generated by Django 3.2.5 on 2021-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20210802_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='participants',
            field=models.ManyToManyField(blank=True, to='meetups.Participants'),
        ),
    ]
