# Generated by Django 3.2.5 on 2021-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_alter_meetups_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participants'),
        ),
    ]
