# Generated by Django 3.2.5 on 2021-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_alter_meetups_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='organizer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
