# Generated by Django 3.2.5 on 2021-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0009_alter_meetups_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='date',
            field=models.DateField(),
        ),
    ]
